ENH micromamba all the places

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -17,18 +17,23 @@ jobs:
           access_token: ${{ github.token }}
 
       - uses: actions/checkout@v2
-
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          python-version: 3.8
-          channels: conda-forge,defaults
-          channel-priority: strict
-          show-channel-urls: true
-
-      - name: configure conda and install code
-        shell: bash -l {0}
+      - name: install micromamba and code
         run: |
-          conda install --quiet --file requirements.txt
+          rm -f ~/.bashrc
+          rm -f ~/.bash_profile
+          rm -f ~/.profile
+          touch ~/.bashrc
+          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
+          ./micromamba shell init -s bash -p ~/micromamba
+          mkdir -p ~/micromamba/pkgs/
+          echo 'set -eo pipefail' >> ~/.bashrc
+          echo 'micromamba activate test' >> ~/.bashrc
+          mv ~/.bashrc ~/.profile
+          export MAMBA_ROOT_PREFIX=~/micromamba
+          export MAMBA_EXE=$(pwd)/micromamba
+          . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
+          micromamba create -f environment.yml -y
+          micromamba activate test
           python -m pip install -e .
 
       - name: lint
diff --git a/.github/workflows/validate-artifact.yml b/.github/workflows/validate-artifact.yml
--- a/.github/workflows/validate-artifact.yml
+++ b/.github/workflows/validate-artifact.yml
@@ -10,22 +10,31 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          python-version: 3.8
-          channels: conda-forge,defaults
-          channel-priority: strict
-          show-channel-urls: true
+      - name: install micromamba and code
+        run: |
+          rm -f ~/.bashrc
+          rm -f ~/.bash_profile
+          rm -f ~/.profile
+          touch ~/.bashrc
+          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
+          ./micromamba shell init -s bash -p ~/micromamba
+          mkdir -p ~/micromamba/pkgs/
+          echo 'set -eo pipefail' >> ~/.bashrc
+          echo 'micromamba activate test' >> ~/.bashrc
+          mv ~/.bashrc ~/.profile
+          export MAMBA_ROOT_PREFIX=~/micromamba
+          export MAMBA_EXE=$(pwd)/micromamba
+          . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
+          micromamba create -f environment.yml -y
+          micromamba activate test
+          python -m pip install -e .
 
-      - name: configure ci and install code
+      - name: configure git
         shell: bash -l {0}
         run: |
           git config pull.rebase false
           git config user.name github-actions
           git config user.email github-actions@github.com
-
-          conda install --quiet --file requirements.txt
-          python -m pip install -e .
 
       - name: validate
         shell: bash -l {0}
